---
#-------------------------------
# General Site Settings

title: Vipin Kumar
logo:
author: themefisher
description: this is meta description
email: vicky7230@gmail.com
phone: +91 8708153354
address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Vipin Kumar <br> Android developer

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: I am a passionate self-taught Android application programmer. I have a proven track record of building apps using best practices, and I am a quick learner capable of adapting to any new technology. I have a thirst for cutting-edge technologies, that comes around. My skill set includes proficiency in Kotlin, Java, MVVM, Jetpack Compose, Coroutines, Dagger2, Dagger Hilt, Firebase, Room DB, CICD and Push Notification.
blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Kotlin, color: "#fdb157", value: "90%" }
  - { name: Android, color: "#9473e6", value: "90%" }
  - { name: Coroutines, color: "#bdecf6", value: "70%" }
  - { name: Android App Developement, color: "#ffbcaa", value: "80%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Software Developer,
      icon: "agrim.jpeg",
      date: "Oct 2016 - Oct 2017",
      organization: "Agrim Education Services",
    }
  - {
      name: Android Engineer,
      icon: "mildly.jpeg",
      date: "Nov 2017 - Apr 2020",
      organization: "Mildly Classic Technologies Pvt. Ltd.",
    }
  - {
      name: Sr. Android Engineer,
      icon: "moe.jpeg",
      date: "Jun 2020 - Present",
      organization: "MoEngage Inc",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Bachelors in Information Technology,
      date: "2011 - 2015",
      organization: "Triguna Sen School of Technology, Assam University, Silchar",
    }
  - {
      name: Higher Secondary Certificat,
      date: "2010",
      organization: "Kendriya Vidalaya, RRL, Jorhat",
    }
  - {
      name: Secondary School Certificate,
      date: "2008",
      organization: "Kendriya Vidalaya, AFS Memaura, Lucknow",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Bug-fixing,
      icon: ti-support,
      description: "I have collaboated wiht clients and developers to help fix their bugs.",
      active,
    }
  - {
      name: Android App Development,
      icon: ti-android,
      description: "I have been developing scalable Android Apps from scratch for last 7 years.",
      active: true, # Add true to select section
    }
  - {
      name: Addign new features,
      icon: ti-pencil-alt2,
      description: "I have worked with multiple clients to enahnce their App by adding new features.",
      active,
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/squel.webp"
    url: "https://play.google.com/store/apps/details?id=com.mildlyclassic.clientbooking"

  - image: "assets/images/portfolio/sequelite.webp"
    url: "https://play.google.com/store/apps/details?id=com.mildlyclassic.sequelda"

  - image: "assets/images/portfolio/ipt2.jpg"
    url: "https://play.google.com/store/apps/details?id=com.app.ipatientd"

  - image: "assets/images/portfolio/sunny.webp"
    url: "https://play.google.com/store/apps/details?id=com.vicky7230.sunny"

  - image: "assets/images/portfolio/revu.webp"
    url: "https://play.google.com/store/apps/details?id=com.app.rivisio"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
